=== enzo2346/projet_web_dynamique/cv.dtd
<!ELEMENT cv(identite, mail, telephone, specialite, experiences, formations, competences)>

<!ELEMENT identite(nom, prenom)>
<!ELEMENT nom(#PCDATA)>
<!ELEMENT prenom(#PCDATA)>
<!ELEMENT mail(#PCDATA)>
<!ELEMENT telephone(#PCDATA)>
<!ELEMENT specialite(#PCDATA)>
<!ELEMENT experiences(experience+)>
<!ELEMENT experience(date, etablissement)>
<!ELEMENT date(#PCDATA)>
<!ELEMENT etablissement(#PCDATA)>
<!ELEMENT formations(formation+)>
<!ELEMENT formation(date, diplome, etablissement)>
<!ELEMENT date(#PCDATA)>
<!ELEMENT diplome(#PCDATA)>
<!ELEMENT etablissement(#PCDATA)>
<!ELEMENT competences(competence+)>
<!ELEMENT competence(#PCDATA)>

=== enzo2346/projet_web_dynamique/cv4.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="cv.xsl"?>
<!DOCTYPE cave SYSTEM "cv.dtd">
<cv>

	<identite>
		<nom>LaCaille</nom>
		<prenom>Landers</prenom>
		<photo>images/icon4.jpg</photo>
	</identite>

	<mail>medecing4@gmail.com</mail>
	<telephone>06 11 11 11 04</telephone>
	<specialite>Généraliste</specialite>

	<experiences>
		<experience>
			<date>2016</date>
			<etablissement>Omnes Santé</etablissement>
		</experience>
		<experience>
			<date>2014</date>
			<etablissement>Polyclinique de Nantes</etablissement>
		</experience>
	</experiences>

	<formations>
		<formation>
			<date>2013</date>
			<diplome>Diplôme d'Etat de Docteur en Médecine</diplome>
			<etablissement> UFR Médecine de Nantes</etablissement>
		</formation>
		<formation>
			<date>2004</date>
			<diplome>Baccalauréat Scientifique</diplome>
			<etablissement>Lycée Victor Hugo Nantes</etablissement>
		</formation>
	</formations>

	<competences>
		<competence>Formateur</competence>
		<competence>A l'écoute</competence>
	</competences>

</cv>

=== enzo2346/projet_web_dynamique/cv13.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="cv.xsl"?>
<!DOCTYPE cave SYSTEM "cv.dtd">
<cv>
	<identite>
		<nom>Couet</nom>
		<prenom>David</prenom>
		<photo>images/icon4.jpg</photo>
	</identite>

	<mail>meddermatologie2@gmail.com</mail>
	<telephone>06 22 22 22 08</telephone>
	<specialite>Dermatologie</specialite>

	<experiences>
		<experience>
			<date>2018</date>
			<etablissement>Omnes Santé</etablissement>
		</experience>
		<experience>
			<date>2014</date>
			<etablissement>Hôpital Maritime de Zuydcoote</etablissement>
		</experience>
	</experiences>

	<formations>
		<formation>
			<date>2013</date>
			<diplome>Diplôme d'Etat de Docteur en Médecine</diplome>
			<etablissement> UFR Médecine de Lille</etablissement>
		</formation>
		<formation>
			<date>2004</date>
			<diplome>Baccalauréat Scientifique</diplome>
			<etablissement>Lycée Carnot Lille</etablissement>
		</formation>
	</formations>

	<competences>
		<competence>Formateur</competence>
		<competence>A l'écoute</competence>
	</competences>
</cv>

=== enzo2346/projet_web_dynamique/cv24.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="cv.xsl"?>
<!DOCTYPE cave SYSTEM "cv.dtd">
<cv>

	<identite>
		<nom>Roussel</nom>
		<prenom>Raina</prenom>
		<photo>images/icon6.jpg</photo>
	</identite>

	<mail>servenceinte@gmail.com</mail>
	<telephone>06 33 33 33 03</telephone>
	<specialite>Biologie de la femme enceinte</specialite>

	<experiences>
		<experience>
			<date>2017</date>
			<etablissement>Omnes Santé</etablissement>
		</experience>
		<experience>
			<date>2012</date>
			<etablissement>Clnique La Mitterie Lomme</etablissement>
		</experience>
	</experiences>

	<formations>
		<formation>
			<date>2012</date>
			<diplome>Diplôme d'Etat de Docteur en Médecine</diplome>
			<etablissement> UFR Médecine de Rennes</etablissement>
		</formation>
		<formation>
			<date>2004</date>
			<diplome>Baccalauréat Scientifique</diplome>
			<etablissement>Lycée Eugène Delacroix Rennes</etablissement>
		</formation>
	</formations>

	<competences>
		<competence>Formateur</competence>
		<competence>Bonne communication</competence>
	</competences>

</cv>

=== enzo2346/projet_web_dynamique/cv6.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="cv.xsl"?>
<!DOCTYPE cave SYSTEM "cv.dtd">
<cv>

	<identite>
		<nom>Labrie</nom>
		<prenom>Moore</prenom>
		<photo>images/icon6.jpg</photo>
	</identite>

	<mail>medaddictologie1@gmail.com</mail>
	<telephone>06 22 22 22 01</telephone>
	<specialite>Addictologie</specialite>

	<experiences>
		<experience>
			<date>2018</date>
			<etablissement>Omnes Santé</etablissement>
		</experience>
		<experience>
			<date>2016</date>
			<etablissement>Centre Hospitalier de Somain</etablissement>
		</experience>
	</experiences>

	<formations>
		<formation>
			<date>2016</date>
			<diplome>Diplôme Universitaire d'addictologie</diplome>
			<etablissement> Faculté de Médecine de Londres</etablissement>
		</formation>
		<formation>
			<date>2013</date>
			<diplome>Diplôme d'Etat de Docteur en Médecine</diplome>
			<etablissement> UFR Médecine de Lille</etablissement>
		</formation>
		<formation>
			<date>2004</date>
			<diplome>Baccalauréat Scientifique</diplome>
			<etablissement>Lycée Edouard Branly Lille</etablissement>
		</formation>
	</formations>

	<competences>
		<competence>Patience</competence>
		<competence>A l'écoute</competence>
	</competences>

</cv>

=== enzo2346/projet_web_dynamique/cv25.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="cv.xsl"?>
<!DOCTYPE cave SYSTEM "cv.dtd">
<cv>

	<identite>
		<nom>Tougas</nom>
		<prenom>Raoul</prenom>
		<photo>images/icon7.jpg</photo>
	</identite>

	<mail>servroutine@gmail.com</mail>
	<telephone>06 33 33 33 04</telephone>
	<specialite>Biologie de la routine</specialite>

	<experiences>
		<experience>
			<date>2020</date>
			<etablissement>Omnes Santé</etablissement>
		</experience>
		<experience>
			<date>2016</date>
			<etablissement>Hôpital Maritime de Zuydcoote</etablissement>
		</experience>
		<experience>
			<date>2010</date>
			<etablissement>Centre Hospitalier de Valenciennes</etablissement>
		</experience>
	</experiences>

	<formations>
		<formation>
			<date>2010</date>
			<diplome>Diplôme d'Etat de Docteur en Médecine</diplome>
			<etablissement> UFR Médecine de Lille</etablissement>
		</formation>
		<formation>
			<date>2000</date>
			<diplome>Baccalauréat Scientifique</diplome>
			<etablissement>Lycée Carnot Valenciennes</etablissement>
		</formation>
	</formations>

	<competences>
		<competence>Formateur</competence>
		<competence>A l'écoute</competence>
	</competences>

</cv>

=== enzo2346/projet_web_dynamique/cv19.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="cv.xsl"?>
<!DOCTYPE cave SYSTEM "cv.dtd">
<cv>

	<identite>
		<nom>Aubé</nom>
		<prenom>Alphonse</prenom>
		<photo>images/icon1.jpg</photo>
	</identite>

	<mail>medist2@gmail.com</mail>
	<telephone>06 22 22 22 14</telephone>
	<specialite>IST</specialite>

	<experiences>
		<experience>
			<date>2017</date>
			<etablissement>Omnes Santé</etablissement>
		</experience>
		<experience>
			<date>2012</date>
			<etablissement>Clnique La Mitterie Lomme</etablissement>
		</experience>
	</experiences>

	<formations>
		<formation>
			<date>2012</date>
			<diplome>Diplôme d'Etat de Docteur en Médecine</diplome>
			<etablissement> UFR Médecine de Rennes</etablissement>
		</formation>
		<formation>
			<date>2004</date>
			<diplome>Baccalauréat Scientifique</diplome>
			<etablissement>Lycée Eugène Delacroix Rennes</etablissement>
		</formation>
	</formations>

	<competences>
		<competence>Formateur</competence>
		<competence>Bonne communication</competence>
	</competences>

</cv>

=== enzo2346/projet_web_dynamique/cv7.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="cv.xsl"?>
<!DOCTYPE cave SYSTEM "cv.dtd">
<cv>

	<identite>
		<nom>Lefebvre</nom>
		<prenom>Auguste</prenom>
		<photo>images/icon7.jpg</photo>
	</identite>

	<mail>medaddictologie2@gmail.com</mail>
	<telephone>06 22 22 22 02</telephone>
	<specialite>Addictologie</specialite>

	<experiences>
		<experience>
			<date>2015</date>
			<etablissement>Omnes Santé</etablissement>
		</experience>
		<experience>
			<date>2010</date>
			<etablissement>Centre Hospitalier de Bernes</etablissement>
		</experience>
	</experiences>

	<formations>
		<formation>
			<date>2010</date>
			<diplome>Diplôme Universitaire d'addictologie</diplome>
			<etablissement> Faculté de Médecine de Bernes</etablissement>
		</formation>
		<formation>
			<date>2007</date>
			<diplome>Diplôme d'Etat de Docteur en Médecine</diplome>
			<etablissement> UFR Médecine de Paris</etablissement>
		</formation>
		<formation>
			<date>2004</date>
			<diplome>Baccalauréat Scientifique</diplome>
			<etablissement>Lycée Edouard Branly Nogent-sur-Marne</etablissement>
		</formation>
	</formations>

	<competences>
		<competence>Patience</competence>
		<competence>A l'écoute</competence>
	</competences>

</cv>
